[package]
name = "ethereum-poller"
version = "0.0.1"
authors = ["Maxim Fischuk"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
tokio-core = "0.1.17"
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
clap = "2.33.0"
config = "0.9.3"
serde_derive = "1.0.102"
serde = "1.0.102"
serde_json = "1.0.41"
zookeeper = "0.5.7"
r2d2 = "0.8.6"
r2d2_pulsar = "0.1.3"
futures = "0.3.1"
pulsar = "0.2.0"